version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - '3456:3456'
    environment:
      - NODE_ENV=production
      - PORT=3456
    restart: unless-stopped
    networks:
      - habit-tracker-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3456
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - habit-tracker-network

networks:
  habit-tracker-network:
    driver: bridge
